root: true
env:
  browser: true
extends:
  - "@chookslint/eslint-config-typescript/strict"
  - "@chookslint/eslint-config-typescript/types"
parserOptions:
  ecmaVersion: 2024
  sourceType: module
  project: true
rules:
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/no-unsafe-enum-comparison": off
  "@typescript-eslint/no-unsafe-return": off
  "@typescript-eslint/no-use-before-define": off
  array-callback-return: off
  camelcase: off
